name: Build SocketCan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04  # 使用 Ubuntu 22.04 作为基础运行环境

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install ARM64 cross-compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu openjdk-17-jdk-headless

    - name: Find OpenJDK Path
      id: jdk-path
      run: |
        JAVA_HOME=$(sudo update-alternatives --query java | grep 'Value: ' | cut -d' ' -f2 | sed 's/\/bin\/java//')
        echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
        echo "Found JAVA_HOME at $JAVA_HOME"

    - name: Verify JDK installation
      run: |
        ls -la $JAVA_HOME/include
        ls -la $JAVA_HOME/include/linux

    - name: Configure CMake
      run: cmake -S ${{ github.workspace }} -B ${{ github.workspace }}/build \
           -DCMAKE_SYSTEM_NAME=Linux \
           -DCMAKE_SYSTEM_PROCESSOR=aarch64 \
           -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc \
           -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ \
           -DJAVA_AWT_INCLUDE_PATH=$JAVA_HOME/include \
           -DJAVA_AWT_LIBRARY=$JAVA_HOME/lib \
           -DJAVA_JVM_LIBRARY=$JAVA_HOME/lib/server \
           -DJAVA_INCLUDE_PATH=$JAVA_HOME/include \
           -DJAVA_INCLUDE_PATH2=$JAVA_HOME/include/linux \
           -DCMAKE_EXPORT_COMPILE_COMMANDS=1

    - name: Build JNI project for ARM64
      run: cmake --build ${{ github.workspace }}/build --verbose

    - name: Verify Build Output
      run: ls -la ${{ github.workspace }}/build

    - name: Output .so File Path
      run: |
        echo "Shared object file generated at: ${{ github.workspace }}/build/libCanSocket.so"
        ls -la ${{ github.workspace }}/build/libCanSocket.so
